[package]
name = "music-organizer"
version = "0.2.0"
authors = ["Saecki <tobiasschmitz2001@gmail.com>"]
edition = "2024"

[lib]
name = "music_organizer"
path = "src/core/lib.rs"

[[bin]]
name = "music-organizer"
path = "src/cli/main.rs"

[profile.release-lto]
inherits = "release"
codegen-units = 1
lto = true

[dependencies]
clap = { version = "4.5", features = ["wrap_help", "cargo", "derive"] }
clap_complete = "4.5"
indexmap = "2.12.1"
regex = "1.12.2"
shellexpand = "3.1.1"
crossbeam-channel = "0.5.15"
crossbeam-deque = "0.8.6"
anyhow = "1.0"

# Audio metadata
id3 = "1.16.3"
mp4ameta = { git = "https://github.com/Saecki/rust-mp4ameta", rev = "a1087f5" }
metaflac = "0.2.8"
opusmeta = "3.0"

# Transcoding to opus
symphonia = { version = "0.5.5", default-features = false, features = ["flac"] }
rubato = "2.0.0"
audioadapter = "3.0.0"
audioadapter-buffers = "3.0.0"
audioadapter-sample = "3.0.0"
opusenc = { version = "0.3.1", features = ["encoder-options"] }
