[package]
name = "music_organizer"
version = "0.2.0"
authors = ["Saecki <tobiasschmitz2001@gmail.com>"]
edition = "2018"

[features]
default = ["checks"]
checks = []

[dependencies]
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
regex = "1.4.2"
walkdir = "2.3.2"
id3 = "0.6.4"
mp4ameta = { path = "../rust-mp4ameta" }
lazy_static = "1.4.0"
colored = "2.0.0"
