[package]
name = "music-organizer"
version = "0.2.0"
authors = ["Saecki <tobiasschmitz2001@gmail.com>"]
edition = "2018"

[lib]
name = "music_organizer"
path = "src/core/lib.rs"

[[bin]]
name = "music-organizer"
path = "src/cli/main.rs"

[dependencies]
clap = { version = "3.0.0-beta.4", features = ["wrap_help"] }
clap_generate = "3.0.0-beta.4"
regex = "1.5.4"
walkdir = "2.3.2"
id3 = "0.6.4"
mp4ameta = "0.11.0"
lazy_static = "1.4.0"
colored = "2.0.0"
shellexpand = "2.1.0"
