[package]
name = "music-organizer"
version = "0.2.0"
authors = ["Saecki <tobiasschmitz2001@gmail.com>"]
edition = "2018"

[lib]
name = "music_organizer"
path = "src/core/lib.rs"

[[bin]]
name = "music-organizer"
path = "src/cli/main.rs"

[dependencies]
clap = { version = "3.0.5", features = ["wrap_help", "cargo"] }
clap_complete = "3.0.2"
regex = "1.5.4"
id3 = "0.6.6"
mp4ameta = "0.11.0"
metaflac = "0.2.5"
lazy_static = "1.4.0"
colored = "2.0.0"
shellexpand = "2.1.0"
crossbeam-channel = "0.5.1"
